// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvlvrbpqxqqqaeihofod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2bHZyYnBxeHFxcWFlaWhvZm9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwNzk3MDQsImV4cCI6MjA4NjY1NTcwNH0.m2qb8kWLvl3Fw49R73ammXHbA2WqtAuQ9wiDF2f3gbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});